### PR TITLE
Andy field names hover (optional part from issue #94)

### PR DESCRIPTION
**Pull request by andy-gale**
hovering over the two fields show a short explanation of each, along the lines of "This is when you would like to picked up" and "This is the latest that you would like to arrive by"

*considered as optional part of issue #37 on our team's Kanban board, copied from issue #94 from the slack announcement link*

hover_screenshot_1

image

Functionality:
-         When cursor is over pick up time form input box a description box should appear to the top right just above
-         Similarly for drop off time form input box

-          these should function independently if cursor is in one input box the hover effect should only display the description for that box, not both.

### CODE REVIEW

**Review by michaelw1985 — APPROVED** [review]
LGTM

**Review by elaineeeho — APPROVED** [review]
LGTM

**Review by ashton-wong — APPROVED** [review]
Tested Locally, LGTM

**Review by andrewpengucsb — DISMISSED** [review]
Would like to see some images in the PR description since this is a frontend change and a qa deployment link

**Comment by andy-gale** [comment]
> Would like to see some images in the PR description since this is a frontend change and a qa deployment link

Added screenshots of new feature to the desciption and specified functionality.
I still cannot deploy anything on dokku since hitting disk quota but functions as expected on local deployment.

**Review by elaineeeho — APPROVED** [review]
LGTM

**Pull request merged**
